'use client';

import { useState, useEffect, useCallback } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { 
  Calendar, MapPin, Clock, Trophy, Users, Ticket,
  CheckCircle, AlertCircle, Clock3, Sparkles, ChevronRight,
  Flag, Award, Plus, RefreshCw, Play
} from 'lucide-react';
import { Button, Badge, Card, Spinner } from '@/components/ui';
import { useAuth } from '@/lib/auth';
import BettingModal from '@/components/BettingModal';
import RacePlayer from '@/components/race/RacePlayer';
import { Event, Horse, Race } from '@/types';

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'https://myracenight-backend-production.up.railway.app';

interface UserBet {
  id: string;
  raceId: string;
  horseId: string;
  horseName: string;
  amount: number;
  odds: string;
  potentialReturn: number;
  status: string;
  actualReturn?: number;
}

export default function AttendeeDashboardPage() {
  const params = useParams();
  const slug = params.slug as string;
  const { user } = useAuth();
  
  const [event, setEvent] = useState<Event | null>(null);
  const [myHorses, setMyHorses] = useState<Horse[]>([]);
  const [myBets, setMyBets] = useState<UserBet[]>([]);
  const [balance, setBalance] = useState<number>(0);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState('');
  
  // Betting modal state
  const [bettingRace, setBettingRace] = useState<Race | null>(null);
  const [bettingHorses, setBettingHorses] = useState<Horse[]>([]);
  const [showBettingModal, setShowBettingModal] = useState(false);
  
  // Race viewing state
  const [watchingRace, setWatchingRace] = useState<Race | null>(null);

  const loadData = useCallback(async () => {
    try {
      const token = localStorage.getItem('accessToken');
      
      // Load event data
      const response = await fetch(`${API_URL}/api/events/by-slug/${slug}`);
      if (!response.ok) throw new Error('Event not found');
      const data = await response.json();
      setEvent(data);
      
      // Filter horses to show user's horses
      if (data.horses) {
        const userHorses = data.horses.filter((h: Horse) => 
          h.userId === user?.id || !h.isAutoGenerated
        );
        setMyHorses(userHorses);
      }

      // Initialize credits if needed and get balance
      if (data.id && token) {
        try {
          // Initialize credits (safe to call multiple times)
          await fetch(`${API_URL}/api/credits/initialize`, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Authorization': `Bearer ${token}`,
            },
            body: JSON.stringify({ eventId: data.id, amount: 50000 }),
          });

          // Get current balance
          const balanceRes = await fetch(`${API_URL}/api/credits/my-balance/${data.id}`, {
            headers: { 'Authorization': `Bearer ${token}` },
          });
          if (balanceRes.ok) {
            const balanceData = await balanceRes.json();
            setBalance(balanceData.balance || 0);
          }

          // Get user's bets
          const betsRes = await fetch(`${API_URL}/api/bets/my-bets?eventId=${data.id}`, {
            headers: { 'Authorization': `Bearer ${token}` },
          });
          if (betsRes.ok) {
            const betsData = await betsRes.json();
            setMyBets(betsData);
          }
        } catch (err) {
          console.error('Error loading credits/bets:', err);
        }
      }
    } catch (err: any) {
      setError(err.message || 'Failed to load event');
    } finally {
      setIsLoading(false);
    }
  }, [slug, user?.id]);

  useEffect(() => {
    loadData();
    
    // Poll for updates every 10 seconds when event is live
    const interval = setInterval(() => {
      if (event?.status === 'LIVE') {
        loadData();
      }
    }, 10000);
    
    return () => clearInterval(interval);
  }, [loadData, event?.status]);

  const handleOpenBetting = async (race: Race) => {
    if (!event) return;
    
    // Get horses for this race
    const raceHorses = (event.horses || []).filter(h => h.raceId === race.id);
    
    setBettingRace(race);
    setBettingHorses(raceHorses);
    setShowBettingModal(true);
  };

  const handleBetPlaced = () => {
    loadData(); // Refresh balance and bets
  };

  const handleWatchRace = (race: Race) => {
    setWatchingRace(race);
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-night flex items-center justify-center">
        <Spinner size="lg" />
      </div>
    );
  }

  if (error || !event) {
    return (
      <div className="min-h-screen bg-night flex items-center justify-center">
        <Card className="text-center p-8 max-w-md">
          <AlertCircle className="w-12 h-12 text-red-400 mx-auto mb-4" />
          <h1 className="text-xl font-bold mb-2">Event Not Found</h1>
          <p className="text-gray-400 mb-6">{error || 'This event may have ended or the link is incorrect.'}</p>
          <Link href="/">
            <Button>Go to Homepage</Button>
          </Link>
        </Card>
      </div>
    );
  }

  const eventDate = new Date(event.eventDate);
  const isEventDay = eventDate.toDateString() === new Date().toDateString();

  const getApprovalBadge = (status: string) => {
    switch (status) {
      case 'APPROVED':
        return <Badge variant="success"><CheckCircle className="w-3 h-3 mr-1" /> Approved</Badge>;
      case 'PENDING':
        return <Badge variant="warning"><Clock3 className="w-3 h-3 mr-1" /> Pending Review</Badge>;
      case 'REJECTED':
        return <Badge variant="error"><AlertCircle className="w-3 h-3 mr-1" /> Needs Changes</Badge>;
      default:
        return <Badge variant="default">{status}</Badge>;
    }
  };

  const getRaceStatusBadge = (race: Race) => {
    switch (race.status) {
      case 'BETTING_OPEN':
        return <Badge variant="live">💰 Betting Open!</Badge>;
      case 'BETTING_CLOSED':
        return <Badge variant="warning">Betting Closed</Badge>;
      case 'IN_PROGRESS':
        return <Badge variant="live">🏇 Racing!</Badge>;
      case 'COMPLETED':
        return <Badge variant="success">✓ Finished</Badge>;
      default:
        return <Badge variant="default">Upcoming</Badge>;
    }
  };

  // Get bets for a specific race
  const getBetsForRace = (raceId: string) => {
    return myBets.filter(b => b.raceId === raceId);
  };

  return (
    <div className="min-h-screen bg-night">
      {/* Header */}
      <header className="bg-night-light border-b border-night-lighter sticky top-0 z-40">
        <div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <span className="text-2xl">🏇</span>
            <span className="font-display font-bold text-xl">MyRaceNight</span>
          </Link>
          
          {/* Balance Display */}
          <div className="flex items-center gap-4">
            <div className="bg-gold/20 px-4 py-2 rounded-lg flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-gold" />
              <span className="font-bold text-gold">{balance.toLocaleString()}</span>
            </div>
            <button 
              onClick={loadData}
              className="p-2 hover:bg-white/10 rounded-lg transition"
              title="Refresh"
            >
              <RefreshCw className="w-5 h-5 text-gray-400" />
            </button>
          </div>
        </div>
      </header>

      <div className="max-w-6xl mx-auto px-4 py-6">
        {/* Event Header */}
        <div className="mb-6">
          <div className="flex items-center gap-2 mb-2">
            <Badge variant={event.status === 'LIVE' ? 'live' : 'default'}>
              {event.status === 'LIVE' ? '🔴 Live Now!' : isEventDay ? '📅 Today!' : event.status}
            </Badge>
          </div>
          <h1 className="text-2xl font-display font-bold mb-1">{event.name}</h1>
          <p className="text-gray-400">Welcome to your race night!</p>
        </div>

        {/* Race Viewer Modal */}
        {watchingRace && (
          <div className="fixed inset-0 bg-black/90 flex items-center justify-center z-50 p-4">
            <div className="max-w-4xl w-full">
              <div className="flex justify-between items-center mb-4">
                <h2 className="text-xl font-bold">{watchingRace.name}</h2>
                <button 
                  onClick={() => setWatchingRace(null)}
                  className="p-2 hover:bg-white/10 rounded-lg"
                >
                  ✕
                </button>
              </div>
              <RacePlayer 
                race={watchingRace}
                onFinish={() => setWatchingRace(null)}
              />
            </div>
          </div>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Main Content */}
          <div className="lg:col-span-2 space-y-6">
            
            {/* Active Races */}
            <Card>
              <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
                <Flag className="w-5 h-5 text-gold" />
                Races
              </h2>

              {event.races && event.races.length > 0 ? (
                <div className="space-y-3">
                  {event.races.map((race) => {
                    const raceBets = getBetsForRace(race.id);
                    const canBet = race.status === 'BETTING_OPEN';
                    const canWatch = race.status === 'IN_PROGRESS' || race.status === 'COMPLETED';
                    
                    return (
                      <div 
                        key={race.id} 
                        className={`p-4 rounded-lg transition ${
                          race.status === 'BETTING_OPEN' 
                            ? 'bg-gold/10 border border-gold/30' 
                            : 'bg-night-lighter'
                        }`}
                      >
                        <div className="flex items-center justify-between mb-2">
                          <div className="flex items-center gap-3">
                            <span className="w-8 h-8 bg-gold/20 text-gold rounded-full flex items-center justify-center text-sm font-bold">
                              {race.raceNumber}
                            </span>
                            <div>
                              <p className="font-medium">{race.name}</p>
                              {race.sponsorName && (
                                <p className="text-xs text-gray-400">Sponsored by {race.sponsorName}</p>
                              )}
                            </div>
                          </div>
                          {getRaceStatusBadge(race)}
                        </div>

                        {/* User's bets on this race */}
                        {raceBets.length > 0 && (
                          <div className="mt-3 space-y-1">
                            <p className="text-xs text-gray-400 font-medium">Your Bets:</p>
                            {raceBets.map((bet) => (
                              <div 
                                key={bet.id}
                                className={`flex items-center justify-between text-sm p-2 rounded ${
                                  bet.status === 'WON' ? 'bg-green-500/10' :
                                  bet.status === 'LOST' ? 'bg-red-500/10' :
                                  'bg-white/5'
                                }`}
                              >
                                <span>
                                  {bet.horseName} @ {bet.odds}
                                </span>
                                <span className={`font-bold ${
                                  bet.status === 'WON' ? 'text-green-400' :
                                  bet.status === 'LOST' ? 'text-red-400' :
                                  'text-gray-300'
                                }`}>
                                  {bet.status === 'WON' 
                                    ? `+${(bet.actualReturn || 0).toLocaleString()}`
                                    : bet.status === 'LOST'
                                    ? `-${bet.amount.toLocaleString()}`
                                    : bet.amount.toLocaleString()
                                  }
                                </span>
                              </div>
                            ))}
                          </div>
                        )}

                        {/* Action Buttons */}
                        <div className="flex gap-2 mt-3">
                          {canBet && (
                            <Button 
                              size="sm" 
                              onClick={() => handleOpenBetting(race)}
                              leftIcon={<Trophy className="w-4 h-4" />}
                            >
                              Place Bet
                            </Button>
                          )}
                          {canWatch && (
                            <Button 
                              size="sm" 
                              variant="secondary"
                              onClick={() => handleWatchRace(race)}
                              leftIcon={<Play className="w-4 h-4" />}
                            >
                              Watch Race
                            </Button>
                          )}
                          {race.status === 'COMPLETED' && race.winningPosition && (
                            <span className="text-sm text-green-400 flex items-center gap-1">
                              <Trophy className="w-4 h-4" />
                              Winner: Position {race.winningPosition}
                            </span>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>
              ) : (
                <div className="text-center py-8 text-gray-400">
                  <Flag className="w-12 h-12 mx-auto mb-3 opacity-50" />
                  <p>Race schedule will be available soon</p>
                </div>
              )}
            </Card>

            {/* My Horses */}
            <Card>
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-lg font-semibold flex items-center gap-2">
                  <Trophy className="w-5 h-5 text-gold" />
                  My Horses
                </h2>
                <Link href={`/events/${slug}/horses/submit`}>
                  <Button size="sm" variant="ghost" leftIcon={<Plus className="w-4 h-4" />}>
                    Add
                  </Button>
                </Link>
              </div>

              {myHorses.length === 0 ? (
                <div className="text-center py-6">
                  <span className="text-3xl mb-2 block">🐴</span>
                  <p className="text-gray-400 text-sm">No horses submitted yet</p>
                </div>
              ) : (
                <div className="space-y-2">
                  {myHorses.slice(0, 5).map((horse) => (
                    <div key={horse.id} className="flex items-center justify-between p-3 bg-night-lighter rounded-lg">
                      <div>
                        <p className="font-medium">{horse.name}</p>
                        <p className="text-xs text-gray-400">Race {horse.raceNumber || 'TBD'}</p>
                      </div>
                      {getApprovalBadge(horse.approvalStatus)}
                    </div>
                  ))}
                </div>
              )}
            </Card>
          </div>

          {/* Sidebar */}
          <div className="space-y-6">
            {/* Credits Balance */}
            <Card className="bg-gradient-to-br from-gold/10 to-transparent border-gold/30">
              <h3 className="font-semibold mb-3 flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-gold" />
                My Credits
              </h3>
              <p className="text-4xl font-bold text-gold mb-1">
                {balance.toLocaleString()}
              </p>
              <p className="text-sm text-gray-400">Available to bet</p>
            </Card>

            {/* My Recent Bets */}
            <Card>
              <h3 className="font-semibold mb-4 flex items-center gap-2">
                <Ticket className="w-5 h-5 text-gold" />
                Recent Bets
              </h3>
              {myBets.length === 0 ? (
                <p className="text-sm text-gray-400 text-center py-4">
                  No bets placed yet
                </p>
              ) : (
                <div className="space-y-2">
                  {myBets.slice(0, 5).map((bet) => (
                    <div 
                      key={bet.id}
                      className={`p-3 rounded-lg text-sm ${
                        bet.status === 'WON' ? 'bg-green-500/10 border border-green-500/30' :
                        bet.status === 'LOST' ? 'bg-red-500/10 border border-red-500/30' :
                        'bg-night-lighter'
                      }`}
                    >
                      <div className="flex justify-between items-start">
                        <div>
                          <p className="font-medium">{bet.horseName}</p>
                          <p className="text-xs text-gray-400">@ {bet.odds}</p>
                        </div>
                        <div className="text-right">
                          <p className={`font-bold ${
                            bet.status === 'WON' ? 'text-green-400' :
                            bet.status === 'LOST' ? 'text-red-400' :
                            'text-white'
                          }`}>
                            {bet.status === 'WON' 
                              ? `+${(bet.actualReturn || 0).toLocaleString()}`
                              : bet.amount.toLocaleString()
                            }
                          </p>
                          <p className="text-xs text-gray-500">{bet.status}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </Card>

            {/* Event Details */}
            <Card>
              <h3 className="font-semibold mb-4 flex items-center gap-2">
                <Calendar className="w-5 h-5 text-gold" />
                Event Details
              </h3>
              <dl className="space-y-3 text-sm">
                <div>
                  <dt className="text-gray-500">Date</dt>
                  <dd className="font-medium">
                    {eventDate.toLocaleDateString('en-IE', {
                      weekday: 'short',
                      day: 'numeric',
                      month: 'short'
                    })}
                  </dd>
                </div>
                <div>
                  <dt className="text-gray-500">Venue</dt>
                  <dd className="font-medium">{event.venue}</dd>
                </div>
                <div>
                  <dt className="text-gray-500">Races</dt>
                  <dd className="font-medium">{event.numberOfRaces} races</dd>
                </div>
              </dl>
            </Card>
          </div>
        </div>
      </div>

      {/* Betting Modal */}
      {showBettingModal && bettingRace && (
        <BettingModal
          isOpen={showBettingModal}
          onClose={() => setShowBettingModal(false)}
          race={bettingRace}
          eventId={event.id}
          horses={bettingHorses}
          balance={balance}
          onBetPlaced={handleBetPlaced}
        />
      )}

      {/* Footer */}
      <footer className="bg-night-light border-t border-night-lighter py-4 mt-8">
        <div className="max-w-6xl mx-auto px-4 text-center text-gray-500 text-sm">
          <p>Powered by <span className="text-gold font-semibold">MyRaceNight</span></p>
        </div>
      </footer>
    </div>
  );
}
