'use client';

import { useState, useEffect, useCallback } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { 
  Calendar, MapPin, Clock, Trophy, Users, Ticket,
  CheckCircle, AlertCircle, Clock3, Sparkles, ChevronRight,
  Flag, Award, Plus, RefreshCw, Play
} from 'lucide-react';
import { Button, Badge, Card, Spinner } from '@/components/ui';
import { useAuth } from '@/lib/auth';
import BettingModal from '@/components/BettingModal';
import RacePlayer from '@/components/race/RacePlayer';
import { Event, Horse, Race } from '@/types';

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'https://myracenight-backend-production.up.railway.app';

interface UserBet {
  id: string;
  raceId: string;
  horseId: string;
  horseName: string;
  amount: number;
  odds: string;
  potentialReturn: number;
  status: string;
  actualReturn?: number;
}

export default function AttendeeDashboardPage() {
  const params = useParams();
  const slug = params.slug as string;
  const { user } = useAuth();
  
  const [event, setEvent] = useState<Event | null>(null);
  const [myHorses, setMyHorses] = useState<Horse[]>([]);
  const [myBets, setMyBets] = useState<UserBet[]>([]);
  const [balance, setBalance] = useState<number>(0);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState('');
  
  // Top-up state
  const [topUpInfo, setTopUpInfo] = useState<{
    available: boolean;
    topUpAmount: number;
    topUpPrice: number;
  } | null>(null);
  const [topUpLoading, setTopUpLoading] = useState(false);
  
  // Betting modal state
  const [bettingRace, setBettingRace] = useState<Race | null>(null);
  const [bettingHorses, setBettingHorses] = useState<Horse[]>([]);
  const [showBettingModal, setShowBettingModal] = useState(false);
  
  // Race viewing state
  const [watchingRace, setWatchingRace] = useState<Race | null>(null);

  const loadData = useCallback(async () => {
    try {
      const token = localStorage.getItem('accessToken');
      
      // Load event data
      const response = await fetch(`${API_URL}/api/events/by-slug/${slug}`);
      if (!response.ok) throw new Error('Event not found');
      const data = await response.json();
      setEvent(data);
      
      // Filter horses to show user's horses
      if (data.horses) {
        const userHorses = data.horses.filter((h: Horse) => 
          h.userId === user?.id || !h.isAutoGenerated
        );
        setMyHorses(userHorses);
      }

      // Initialize credits if needed and get balance
      if (data.id && token) {
        try {
          // Initialize credits (safe to call multiple times)
          await fetch(`${API_URL}/api/credits/initialize`, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Authorization': `Bearer ${token}`,
            },
            body: JSON.stringify({ eventId: data.id, amount: 50000 }),
          });

          // Get current balance
          const balanceRes = await fetch(`${API_URL}/api/credits/my-balance/${data.id}`, {
            headers: { 'Authorization': `Bearer ${token}` },
          });
          if (balanceRes.ok) {
            const balanceData = await balanceRes.json();
            setBalance(balanceData.balance || 0);
          }

          // Get top-up info
          const topUpRes = await fetch(`${API_URL}/api/credits/top-up-info/${data.id}`, {
            headers: { 'Authorization': `Bearer ${token}` },
          });
          if (topUpRes.ok) {
            const topUpData = await topUpRes.json();
            setTopUpInfo(topUpData);
          }

          // Get user's bets
          const betsRes = await fetch(`${API_URL}/api/bets/my-bets?eventId=${data.id}`, {
            headers: { 'Authorization': `Bearer ${token}` },
          });
          if (betsRes.ok) {
            const betsData = await betsRes.json();
            setMyBets(betsData);
          }
        } catch (err) {
          console.error('Error loading credits/bets:', err);
        }
      }
    } catch (err: any) {
      setError(err.message || 'Failed to load event');
    } finally {
      setIsLoading(false);
    }
  }, [slug, user?.id]);

  useEffect(() => {
    loadData();
    
    // Poll for updates every 10 seconds when event is live
    const interval = setInterval(() => {
      if (event?.status === 'LIVE') {
        loadData();
      }
    }, 10000);
    
    return () => clearInterval(interval);
  }, [loadData, event?.status]);

  const handleOpenBetting = async (race: Race) => {
    if (!event) return;
    
    // Get horses for this race
    const raceHorses = (event.horses || []).filter(h => h.raceId === race.id);
    
    setBettingRace(race);
    setBettingHorses(raceHorses);
    setShowBettingModal(true);
  };

  const handleBetPlaced = () => {
    loadData(); // Refresh balance and bets
  };

  const handleWatchRace = (race: Race) => {
    setWatchingRace(race);
  };

  const handleTopUp = async () => {
    if (!event || !topUpInfo?.available) return;
    
    const confirmed = confirm(
      `Top up ${topUpInfo.topUpAmount.toLocaleString()} credits for €${topUpInfo.topUpPrice.toFixed(2)}?\n\nThis is a one-time offer per event.`
    );
    
    if (!confirmed) return;
    
    setTopUpLoading(true);
    try {
      const token = localStorage.getItem('accessToken');
      const response = await fetch(`${API_URL}/api/credits/top-up`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
        body: JSON.stringify({ eventId: event.id }),
      });
      
      const data = await response.json();
      
      if (data.success) {
        setBalance(data.newBalance);
        setTopUpInfo({ ...topUpInfo, available: false });
        alert(`Success! ${data.creditsAdded.toLocaleString()} credits added to your balance.`);
      } else {
        alert(data.message || 'Failed to process top-up');
      }
    } catch (err) {
      alert('Failed to process top-up. Please try again.');
    } finally {
      setTopUpLoading(false);
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-night flex items-center justify-center">
        <Spinner size="lg" />
      </div>
    );
  }

  if (error || !event) {
    return (
      <div className="min-h-screen bg-night flex items-center justify-center">
        <Card className="text-center p-8 max-w-md">
          <AlertCircle className="w-12 h-12 text-red-400 mx-auto mb-4" />
          <h1 className="text-xl font-bold mb-2">Event Not Found</h1>
          <p className="text-gray-400 mb-6">{error || 'This event may have ended or the link is incorrect.'}</p>
          <Link href="/">
            <Button>Go to Homepage</Button>
          </Link>
        </Card>
      </div>
    );
  }

  const eventDate = new Date(event.eventDate);
  const isEventDay = eventDate.toDateString() === new Date().toDateString();

  const getApprovalBadge = (status: string) => {
    switch (status) {
      case 'APPROVED':
        return <Badge variant="success"><CheckCircle className="w-3 h-3 mr-1" /> Approved</Badge>;
      case 'PENDING':
        return <Badge variant="warning"><Clock3 className="w-3 h-3 mr-1" /> Pending Review</Badge>;
      case 'REJECTED':
        return <Badge variant="error"><AlertCircle className="w-3 h-3 mr-1" /> Needs Changes</Badge>;
      default:
        return <Badge variant="default">{status}</Badge>;
    }
  };

  const getRaceStatusBadge = (race: Race) => {
    switch (race.status) {
      case 'BETTING_OPEN':
        return <Badge variant="live">💰 Betting Open!</Badge>;
      case 'BETTING_CLOSED':
        return <Badge variant="warning">Betting Closed</Badge>;
      case 'IN_PROGRESS':
        return <Badge variant="live">🏇 Racing!</Badge>;
      case 'COMPLETED':
        return <Badge variant="success">✓ Finished</Badge>;
      default:
        return <Badge variant="default">Upcoming</Badge>;
    }
  };

  // Get bets for a specific race
  const getBetsForRace = (raceId: string) => {
    return myBets.filter(b => b.raceId === raceId);
  };

  return (
    <div className="min-h-screen bg-night">
      {/* Header - Mobile optimized */}
      <header className="bg-night-light border-b border-night-lighter sticky top-0 z-40 safe-top">
        <div className="max-w-6xl mx-auto px-3 sm:px-4 py-2 sm:py-3 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-1.5 sm:gap-2">
            <span className="text-xl sm:text-2xl">🏇</span>
            <span className="font-display font-bold text-base sm:text-xl hidden xs:inline">MyRaceNight</span>
          </Link>
          
          {/* Balance Display - Compact on mobile */}
          <div className="flex items-center gap-2 sm:gap-4">
            <div className="bg-gold/20 px-2.5 sm:px-4 py-1.5 sm:py-2 rounded-lg flex items-center gap-1.5 sm:gap-2">
              <Sparkles className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-gold" />
              <span className="font-bold text-gold text-sm sm:text-base">{balance.toLocaleString()}</span>
            </div>
            <button 
              onClick={loadData}
              className="p-2 hover:bg-white/10 rounded-lg transition min-h-[44px] min-w-[44px] flex items-center justify-center"
              title="Refresh"
            >
              <RefreshCw className="w-5 h-5 text-gray-400" />
            </button>
          </div>
        </div>
      </header>

      <div className="max-w-6xl mx-auto px-3 sm:px-4 py-4 sm:py-6">
        {/* Event Header */}
        <div className="mb-4 sm:mb-6">
          <div className="flex items-center gap-2 mb-2">
            <Badge variant={event.status === 'LIVE' ? 'live' : 'default'}>
              {event.status === 'LIVE' ? '🔴 Live Now!' : isEventDay ? '📅 Today!' : event.status}
            </Badge>
          </div>
          <h1 className="text-xl sm:text-2xl font-display font-bold mb-1">{event.name}</h1>
          <p className="text-gray-400 text-sm sm:text-base">Welcome to your race night!</p>
        </div>

        {/* Race Viewer Modal - Full screen on mobile */}
        {watchingRace && (
          <div className="fixed inset-0 bg-black/95 flex items-center justify-center z-50 p-2 sm:p-4">
            <div className="w-full max-w-4xl h-full sm:h-auto flex flex-col">
              <div className="flex justify-between items-center mb-2 sm:mb-4 p-2">
                <h2 className="text-lg sm:text-xl font-bold">{watchingRace.name}</h2>
                <button 
                  onClick={() => setWatchingRace(null)}
                  className="p-3 hover:bg-white/10 rounded-lg min-h-[44px] min-w-[44px] flex items-center justify-center"
                >
                  ✕
                </button>
              </div>
              <div className="flex-1 overflow-hidden">
                <RacePlayer 
                  race={watchingRace}
                  onFinish={() => setWatchingRace(null)}
                />
              </div>
            </div>
          </div>
        )}

        {/* Mobile: Sidebar content first (credits), then races */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-6">
          {/* Mobile Credits Summary - Show at top on mobile only */}
          <div className="lg:hidden">
            <Card className="bg-gradient-to-br from-gold/10 to-transparent border-gold/30">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <Sparkles className="w-5 h-5 text-gold" />
                  <div>
                    <p className="text-2xl font-bold text-gold">{balance.toLocaleString()}</p>
                    <p className="text-xs text-gray-400">Credits available</p>
                  </div>
                </div>
                {/* Top-up Button - Mobile */}
                {topUpInfo?.available && event?.status === 'LIVE' && (
                  <Button 
                    size="sm" 
                    onClick={handleTopUp}
                    isLoading={topUpLoading}
                    leftIcon={<Plus className="w-4 h-4" />}
                  >
                    Top Up
                  </Button>
                )}
              </div>
            </Card>
          </div>

          {/* Main Content */}
          <div className="lg:col-span-2 space-y-4 sm:space-y-6">
            
            {/* Active Races */}
            <Card>
              <h2 className="text-lg sm:text-xl font-semibold mb-3 sm:mb-4 flex items-center gap-2">
                <Flag className="w-5 h-5 text-gold" />
                Races
              </h2>

              {event.races && event.races.length > 0 ? (
                <div className="space-y-3">
                  {event.races.map((race) => {
                    const raceBets = getBetsForRace(race.id);
                    const canBet = race.status === 'BETTING_OPEN';
                    const canWatch = race.status === 'IN_PROGRESS' || race.status === 'COMPLETED';
                    
                    return (
                      <div 
                        key={race.id} 
                        className={`p-3 sm:p-4 rounded-lg transition ${
                          race.status === 'BETTING_OPEN' 
                            ? 'bg-gold/10 border border-gold/30' 
                            : 'bg-night-lighter'
                        }`}
                      >
                        {/* Race header - stack on mobile */}
                        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 mb-2">
                          <div className="flex items-center gap-2 sm:gap-3">
                            <span className="w-8 h-8 bg-gold/20 text-gold rounded-full flex items-center justify-center text-sm font-bold flex-shrink-0">
                              {race.raceNumber}
                            </span>
                            <div className="min-w-0">
                              <p className="font-medium text-sm sm:text-base truncate">{race.name}</p>
                              {race.sponsorName && (
                                <p className="text-xs text-gray-400 truncate">Sponsored by {race.sponsorName}</p>
                              )}
                            </div>
                          </div>
                          <div className="flex-shrink-0 ml-10 sm:ml-0">
                            {getRaceStatusBadge(race)}
                          </div>
                        </div>

                        {/* User's bets on this race */}
                        {raceBets.length > 0 && (
                          <div className="mt-3 space-y-1">
                            <p className="text-xs text-gray-400 font-medium">Your Bets:</p>
                            {raceBets.map((bet) => (
                              <div 
                                key={bet.id}
                                className={`flex items-center justify-between text-sm p-2 rounded ${
                                  bet.status === 'WON' ? 'bg-green-500/10' :
                                  bet.status === 'LOST' ? 'bg-red-500/10' :
                                  'bg-white/5'
                                }`}
                              >
                                <span className="truncate mr-2">
                                  {bet.horseName} @ {bet.odds}
                                </span>
                                <span className={`font-bold flex-shrink-0 ${
                                  bet.status === 'WON' ? 'text-green-400' :
                                  bet.status === 'LOST' ? 'text-red-400' :
                                  'text-gray-300'
                                }`}>
                                  {bet.status === 'WON' 
                                    ? `+${(bet.actualReturn || 0).toLocaleString()}`
                                    : bet.status === 'LOST'
                                    ? `-${bet.amount.toLocaleString()}`
                                    : bet.amount.toLocaleString()
                                  }
                                </span>
                              </div>
                            ))}
                          </div>
                        )}

                        {/* Action Buttons - Full width on mobile */}
                        <div className="flex flex-col sm:flex-row gap-2 mt-3">
                          {canBet && (
                            <Button 
                              size="sm" 
                              className="w-full sm:w-auto"
                              onClick={() => handleOpenBetting(race)}
                              leftIcon={<Trophy className="w-4 h-4" />}
                            >
                              Place Bet
                            </Button>
                          )}
                          {canWatch && (
                            <Button 
                              size="sm" 
                              variant="secondary"
                              className="w-full sm:w-auto"
                              onClick={() => handleWatchRace(race)}
                              leftIcon={<Play className="w-4 h-4" />}
                            >
                              Watch Race
                            </Button>
                          )}
                          {race.status === 'COMPLETED' && race.winningPosition && (
                            <span className="text-sm text-green-400 flex items-center justify-center sm:justify-start gap-1 py-2">
                              <Trophy className="w-4 h-4" />
                              Winner: Position {race.winningPosition}
                            </span>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>
              ) : (
                <div className="text-center py-6 sm:py-8 text-gray-400">
                  <Flag className="w-10 h-10 sm:w-12 sm:h-12 mx-auto mb-3 opacity-50" />
                  <p className="text-sm sm:text-base">Race schedule will be available soon</p>
                </div>
              )}
            </Card>

            {/* My Horses */}
            <Card>
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-lg font-semibold flex items-center gap-2">
                  <Trophy className="w-5 h-5 text-gold" />
                  My Horses
                </h2>
                <Link href={`/events/${slug}/horses/submit`}>
                  <Button size="sm" variant="ghost" leftIcon={<Plus className="w-4 h-4" />}>
                    Add
                  </Button>
                </Link>
              </div>

              {myHorses.length === 0 ? (
                <div className="text-center py-6">
                  <span className="text-3xl mb-2 block">🐴</span>
                  <p className="text-gray-400 text-sm">No horses submitted yet</p>
                </div>
              ) : (
                <div className="space-y-2">
                  {myHorses.slice(0, 5).map((horse) => (
                    <div key={horse.id} className="flex items-center justify-between p-3 bg-night-lighter rounded-lg">
                      <div>
                        <p className="font-medium">{horse.name}</p>
                        <p className="text-xs text-gray-400">Race {horse.raceNumber || 'TBD'}</p>
                      </div>
                      {getApprovalBadge(horse.approvalStatus)}
                    </div>
                  ))}
                </div>
              )}
            </Card>
          </div>

          {/* Sidebar */}
          <div className="space-y-4 sm:space-y-6">
            {/* Credits Balance - Hidden on mobile (shown at top) */}
            <Card className="hidden lg:block bg-gradient-to-br from-gold/10 to-transparent border-gold/30">
              <h3 className="font-semibold mb-3 flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-gold" />
                My Credits
              </h3>
              <p className="text-4xl font-bold text-gold mb-1">
                {balance.toLocaleString()}
              </p>
              <p className="text-sm text-gray-400 mb-3">Available to bet</p>
              
              {/* Top-up Button */}
              {topUpInfo?.available && event?.status === 'LIVE' && (
                <Button 
                  size="sm" 
                  className="w-full"
                  onClick={handleTopUp}
                  isLoading={topUpLoading}
                  leftIcon={<Plus className="w-4 h-4" />}
                >
                  Top Up +{topUpInfo.topUpAmount.toLocaleString()} (€{topUpInfo.topUpPrice.toFixed(2)})
                </Button>
              )}
              {topUpInfo && !topUpInfo.available && (
                <p className="text-xs text-gray-500 text-center">
                  ✓ Top-up already used
                </p>
              )}
            </Card>

            {/* My Recent Bets */}
            <Card>
              <h3 className="font-semibold mb-3 sm:mb-4 flex items-center gap-2">
                <Ticket className="w-5 h-5 text-gold" />
                Recent Bets
              </h3>
              {myBets.length === 0 ? (
                <p className="text-sm text-gray-400 text-center py-4">
                  No bets placed yet
                </p>
              ) : (
                <div className="space-y-2">
                  {myBets.slice(0, 5).map((bet) => (
                    <div 
                      key={bet.id}
                      className={`p-3 rounded-lg text-sm ${
                        bet.status === 'WON' ? 'bg-green-500/10 border border-green-500/30' :
                        bet.status === 'LOST' ? 'bg-red-500/10 border border-red-500/30' :
                        'bg-night-lighter'
                      }`}
                    >
                      <div className="flex justify-between items-start">
                        <div>
                          <p className="font-medium">{bet.horseName}</p>
                          <p className="text-xs text-gray-400">@ {bet.odds}</p>
                        </div>
                        <div className="text-right">
                          <p className={`font-bold ${
                            bet.status === 'WON' ? 'text-green-400' :
                            bet.status === 'LOST' ? 'text-red-400' :
                            'text-white'
                          }`}>
                            {bet.status === 'WON' 
                              ? `+${(bet.actualReturn || 0).toLocaleString()}`
                              : bet.amount.toLocaleString()
                            }
                          </p>
                          <p className="text-xs text-gray-500">{bet.status}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </Card>

            {/* Event Details */}
            <Card>
              <h3 className="font-semibold mb-4 flex items-center gap-2">
                <Calendar className="w-5 h-5 text-gold" />
                Event Details
              </h3>
              <dl className="space-y-3 text-sm">
                <div>
                  <dt className="text-gray-500">Date</dt>
                  <dd className="font-medium">
                    {eventDate.toLocaleDateString('en-IE', {
                      weekday: 'short',
                      day: 'numeric',
                      month: 'short'
                    })}
                  </dd>
                </div>
                <div>
                  <dt className="text-gray-500">Venue</dt>
                  <dd className="font-medium">{event.venue}</dd>
                </div>
                <div>
                  <dt className="text-gray-500">Races</dt>
                  <dd className="font-medium">{event.numberOfRaces} races</dd>
                </div>
              </dl>
            </Card>
          </div>
        </div>
      </div>

      {/* Betting Modal */}
      {showBettingModal && bettingRace && (
        <BettingModal
          isOpen={showBettingModal}
          onClose={() => setShowBettingModal(false)}
          race={bettingRace}
          eventId={event.id}
          horses={bettingHorses}
          balance={balance}
          onBetPlaced={handleBetPlaced}
        />
      )}

      {/* Footer */}
      <footer className="bg-night-light border-t border-night-lighter py-4 mt-8">
        <div className="max-w-6xl mx-auto px-4 text-center text-gray-500 text-sm">
          <p>Powered by <span className="text-gold font-semibold">MyRaceNight</span></p>
        </div>
      </footer>
    </div>
  );
}
