'use client';

import { useState } from 'react';
import { AlertCircle, Sparkles, X, Users, CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui';

interface RaceInfo {
  raceId: string;
  raceName: string;
  raceNumber: number;
  horseCounts: {
    assigned: number;
    autoGenerated: number;
    total: number;
  };
  needsAutoFill: boolean;
  positionsToFill: number;
}

interface ConfirmCommentaryModalProps {
  raceInfo: RaceInfo;
  totalPositions?: number;
  isGenerating: boolean;
  onConfirm: () => void;
  onCancel: () => void;
}

export function ConfirmCommentaryModal({
  raceInfo,
  totalPositions = 11,
  isGenerating,
  onConfirm,
  onCancel,
}: ConfirmCommentaryModalProps) {
  const { raceName, raceNumber, horseCounts, needsAutoFill, positionsToFill } = raceInfo;

  return (
    <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50 p-4">
      <div className="bg-night-light rounded-xl max-w-md w-full">
        {/* Header */}
        <div className="p-6 border-b border-night-lighter flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-gold/20 rounded-full flex items-center justify-center">
              <Sparkles className="w-5 h-5 text-gold" />
            </div>
            <h2 className="text-xl font-bold">Generate Commentary</h2>
          </div>
          <button
            onClick={onCancel}
            disabled={isGenerating}
            className="p-2 hover:bg-white/10 rounded-lg disabled:opacity-50"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6">
          {/* Race Info */}
          <div className="mb-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-12 h-12 bg-gold/10 rounded-xl flex items-center justify-center">
                <span className="text-xl font-bold text-gold">{raceNumber}</span>
              </div>
              <div>
                <p className="font-semibold">{raceName}</p>
                <p className="text-sm text-gray-400">Race {raceNumber}</p>
              </div>
            </div>
          </div>

          {/* Horse Counts */}
          <div className="bg-night rounded-lg p-4 mb-6">
            <div className="flex items-center gap-3 mb-3">
              <Users className="w-5 h-5 text-gray-400" />
              <span className="font-medium">Horse Lineup</span>
            </div>
            
            <div className="space-y-2">
              <div className="flex justify-between items-center">
                <span className="text-gray-400">Your horses assigned</span>
                <span className="font-bold text-green-400">{horseCounts.assigned}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-gray-400">Positions needed</span>
                <span className="font-bold">{totalPositions}</span>
              </div>
              
              {/* Progress bar */}
              <div className="mt-3">
                <div className="h-2 bg-night-lighter rounded-full overflow-hidden">
                  <div 
                    className="h-full bg-gradient-to-r from-green-500 to-gold rounded-full transition-all"
                    style={{ width: `${(horseCounts.assigned / totalPositions) * 100}%` }}
                  />
                </div>
                <p className="text-xs text-gray-500 mt-1 text-center">
                  {horseCounts.assigned} / {totalPositions} positions filled
                </p>
              </div>
            </div>
          </div>

          {/* Auto-fill Warning */}
          {needsAutoFill && (
            <div className="bg-amber-500/10 border border-amber-500/30 rounded-lg p-4 mb-6">
              <div className="flex items-start gap-3">
                <AlertCircle className="w-5 h-5 text-amber-400 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="font-medium text-amber-400">Auto-Fill Required</p>
                  <p className="text-sm text-gray-300 mt-1">
                    <strong>{positionsToFill}</strong> empty positions will be automatically 
                    filled with placeholder horses. Your horses will be assigned to the 
                    most exciting positions (1st, 2nd, 3rd, 4th place).
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* All horses assigned */}
          {!needsAutoFill && (
            <div className="bg-green-500/10 border border-green-500/30 rounded-lg p-4 mb-6">
              <div className="flex items-start gap-3">
                <CheckCircle2 className="w-5 h-5 text-green-400 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="font-medium text-green-400">All Positions Filled</p>
                  <p className="text-sm text-gray-300 mt-1">
                    All {totalPositions} positions are filled. Ready to generate commentary!
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* What happens next */}
          <div className="text-sm text-gray-400 mb-6">
            <p className="font-medium text-gray-300 mb-2">What happens next:</p>
            <ol className="list-decimal list-inside space-y-1">
              {needsAutoFill && (
                <li>Empty positions filled with random horses</li>
              )}
              <li>Your horses assigned to top positions</li>
              <li>Full race commentary generated (~3 minutes audio)</li>
              <li>Audio uploaded and ready for playback</li>
            </ol>
          </div>
        </div>

        {/* Actions */}
        <div className="p-6 border-t border-night-lighter flex gap-3">
          <Button
            variant="ghost"
            onClick={onCancel}
            disabled={isGenerating}
            className="flex-1"
          >
            Cancel
          </Button>
          <Button
            onClick={onConfirm}
            disabled={isGenerating}
            isLoading={isGenerating}
            leftIcon={<Sparkles className="w-4 h-4" />}
            className="flex-1"
          >
            {isGenerating ? 'Generating...' : 'Generate Commentary'}
          </Button>
        </div>
      </div>
    </div>
  );
}
