// User types
export interface User {
  id: string;
  email?: string;
  firstName: string;
  lastName: string;
  role: UserRole;
  avatarUrl?: string;
  phone?: string;
  authMethod?: AuthMethod;
  ageVerified?: boolean;
  mustChangePassword?: boolean;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export type UserRole = 'SUPER_ADMIN' | 'ORGANISER' | 'HOST' | 'PLAYER';
export type AuthMethod = 'EMAIL' | 'PHONE';

// Auth types
export interface AuthResponse {
  user: User;
  accessToken: string;
  refreshToken: string;
}

export interface LoginCredentials {
  email?: string;
  password?: string;
  phone?: string;
  pin?: string;
}

export interface RegisterData {
  email?: string;
  password?: string;
  phone?: string;
  pin?: string;
  firstName: string;
  lastName: string;
  authMethod?: AuthMethod;
  ageVerified?: boolean;
}

// Club types
export interface Club {
  id: string;
  name: string;
  description: string;
  logoUrl?: string;
  sport: string;
  county: string;
  contactEmail: string;
  contactPhone: string;
  achievements: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  members?: ClubMember[];
  events?: Event[];
}

export interface ClubMember {
  id: string;
  userId: string;
  clubId: string;
  role: ClubMemberRole;
  joinedAt: string;
  user?: User;
}

export type ClubMemberRole = 'OWNER' | 'ADMIN' | 'MEMBER';

// Event types
export interface Event {
  id: string;
  clubId: string;
  organiserId: string;
  name: string;
  slug: string;
  description: string;
  venue: string;
  venueAddress: string;
  address: string;
  eventDate: string;
  ticketPrice: number;
  maxAttendees: number;
  numberOfRaces: number;
  horsesPerRace: number;
  maxHorsesPerPerson: number;
  horseDeadline: string;
  status: EventStatus;
  contentFilterMode: string;
  commentaryPersona: CommentaryPersona;
  insideJokes: string[];
  welcomeDrinkIncluded: boolean;
  createdAt: string;
  updatedAt: string;
  club?: Club;
  tickets?: Ticket[];
  horses?: Horse[];
  races?: Race[];
}

export type EventStatus = 'DRAFT' | 'PUBLISHED' | 'RACECARD_PUBLISHED' | 'LIVE' | 'COMPLETED' | 'CANCELLED';
export type CommentaryPersona = 'CHELTENHAM_PRO' | 'COMEDY_ROASTER' | 'LOCAL_CHARACTER' | 'SPORTS_PUNDIT';

// Ticket types
export interface Ticket {
  id: string;
  eventId: string;
  userId: string;
  qrCode: string;
  ticketNumber?: string;
  status: TicketStatus;
  price: number;           // Backend field name
  pricePaid?: number;      // Alias for backwards compatibility
  startingCredits: number;
  purchasedAt?: string;
  createdAt?: string;
  checkedInAt?: string;
  event?: Event;
  user?: User;
}

export type TicketStatus = 'PURCHASED' | 'CHECKED_IN' | 'CANCELLED' | 'REFUNDED';

// Horse types
export interface Horse {
  id: string;
  eventId: string;
  userId?: string;
  raceId?: string;
  name: string;
  horseName: string; // Alias for name for consistency
  ownerName: string;
  backstory: string;
  catchphrase: string;
  jockeyName: string;
  jockeyPersonality: string;
  voiceNoteUrl: string;
  voiceNoteDuration: number;
  approvalStatus: HorseApprovalStatus;
  approvalNotes: string;
  raceNumber: number;
  position: number;
  createdAt: string;
  updatedAt?: string;
  event?: Event;
  user?: User;
  // New fields for v39 (auto-fill & race card)
  isAutoGenerated?: boolean;
  jsonHorseId?: string;
  silks?: string;
  odds?: string;
  finalPosition?: number;
  resultCommentary?: string;
}

export type HorseApprovalStatus = 'PENDING' | 'APPROVED' | 'FLAGGED' | 'REJECTED';

// Race types
export interface Race {
  id: string;
  eventId: string;
  raceNumber: number;
  name: string;
  sponsorName: string;
  sponsorLogoUrl: string;
  sponsorDescription: string;
  sponsorWebsite: string;
  videoId: string;
  videoUrl: string; // URL to the actual video file
  status: RaceStatus;
  requiredHorseCount: number; // Number of horses required (from metadata JSON)
  bettingOpenedAt: string;
  bettingClosedAt: string;
  startedAt: string;
  completedAt: string;
  commentaryScript: string;
  commentaryAudioUrl: string;
  winningPosition: number;
  createdAt: string;
  updatedAt: string;
  event?: Event;
  bets?: Bet[];
}

// Race statuses - PENDING is removed
export type RaceStatus = 
  | 'SLOTS_INCOMPLETE'      // Not all horse slots filled (count from metadata)
  | 'READY_FOR_COMMENTARY'  // All slots filled, commentary not yet generated
  | 'READY_TO_RACE'         // Commentary generated, race is LOCKED and ready
  | 'BETTING_OPEN'          // Host has opened betting
  | 'BETTING_CLOSED'        // Betting closed, ready to play race
  | 'IN_PROGRESS'           // Race video is playing
  | 'COMPLETED';            // Race finished, bets settled

// Bet types
export interface Bet {
  id: string;
  raceId: string;
  horseId: string;
  userId: string;
  amount: number;
  odds: number;
  potentialWinnings: number;
  status: BetStatus;
  createdAt: string;
  settledAt?: string;
  race?: Race;
  horse?: Horse;
  user?: User;
}

export type BetStatus = 'PENDING' | 'WON' | 'LOST' | 'CANCELLED';

// Credits types
export interface CreditBalance {
  userId: string;
  eventId: string;
  balance: number;
}

export interface CreditLedger {
  id: string;
  userId: string;
  eventId: string;
  amount: number;
  type: TransactionType;
  description: string;
  referenceId?: string;
  createdAt: string;
}

export type TransactionType = 'TICKET_PURCHASE' | 'BET_PLACED' | 'BET_WON' | 'BONUS' | 'REFUND';

// Notification types
export interface Notification {
  id: string;
  userId: string;
  type: NotificationType;
  title: string;
  message: string;
  body: string;
  status: NotificationStatus;
  createdAt: string;
  readAt?: string;
}

export type NotificationType = 'HORSE_APPROVED' | 'HORSE_REJECTED' | 'RACE_STARTING' | 'BET_WON' | 'EVENT_REMINDER';
export type NotificationStatus = 'UNREAD' | 'READ' | 'ARCHIVED';

// Dashboard stats
export interface DashboardStats {
  totalEvents: number;
  liveEvents: number;
  totalTicketsSold: number;
  totalRevenue: number;
  upcomingEvents: Event[];
  recentActivity: ActivityItem[];
}

export interface ActivityItem {
  id: string;
  type: 'ticket_sold' | 'horse_submitted' | 'event_published' | 'race_completed';
  description: string;
  timestamp: string;
}
