'use client';

import { Trophy, User, Shirt, Star } from 'lucide-react';
import { Badge } from '@/components/ui';

interface HorseCard {
  id: string;
  position: number;
  name: string;
  ownerName: string;
  jockeyName: string;
  silks: string;
  odds: string;
  oddsNumeric: number;
  isAutoGenerated: boolean;
  age?: number;
  weight?: string;
  country?: string;
}

interface RaceCardData {
  raceId: string;
  raceNumber: number;
  raceName: string;
  eventName: string;
  totalHorses: number;
  horses: HorseCard[];
  lockedAt: string;
  commentaryReady: boolean;
}

interface RaceCardDisplayProps {
  raceCard: RaceCardData;
  onClose?: () => void;
}

export function RaceCardDisplay({ raceCard, onClose }: RaceCardDisplayProps) {
  // Format odds display (favorite indicator)
  const isFavorite = (index: number) => index === 0;
  const isPodiumPosition = (index: number) => index < 3;

  return (
    <div className="bg-night-light rounded-xl overflow-hidden">
      {/* Header */}
      <div className="p-4 bg-gradient-to-r from-gold/20 to-transparent border-b border-night-lighter">
        <div className="flex items-center justify-between">
          <div>
            <div className="flex items-center gap-2">
              <div className="w-10 h-10 bg-gold/20 rounded-full flex items-center justify-center">
                <span className="text-lg font-bold text-gold">{raceCard.raceNumber}</span>
              </div>
              <div>
                <h3 className="font-bold text-lg">{raceCard.raceName}</h3>
                <p className="text-sm text-gray-400">{raceCard.totalHorses} runners • Commentary Ready</p>
              </div>
            </div>
          </div>
          {raceCard.commentaryReady && (
            <Badge variant="success">Locked In ✓</Badge>
          )}
        </div>
      </div>

      {/* Horses List - Sorted by Odds (Favorite First) */}
      <div className="p-4">
        <div className="text-xs text-gray-500 uppercase tracking-wider mb-3 flex items-center gap-2">
          <Star className="w-3 h-3" />
          Runners (Sorted by Odds - Favorite First)
        </div>
        
        <div className="space-y-2">
          {raceCard.horses.map((horse, index) => (
            <div
              key={horse.id}
              className={`p-3 rounded-lg border transition-colors ${
                isFavorite(index)
                  ? 'bg-gold/10 border-gold/30'
                  : isPodiumPosition(index)
                  ? 'bg-night border-night-lighter'
                  : 'bg-night-lighter/30 border-transparent'
              }`}
            >
              <div className="flex items-center gap-3">
                {/* Rank/Odds Position */}
                <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold ${
                  isFavorite(index)
                    ? 'bg-gold text-black'
                    : isPodiumPosition(index)
                    ? 'bg-gray-600 text-white'
                    : 'bg-night-lighter text-gray-400'
                }`}>
                  {index + 1}
                </div>

                {/* Horse Info */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="font-semibold truncate">{horse.name}</span>
                    {isFavorite(index) && (
                      <Badge variant="warning" className="text-xs">FAV</Badge>
                    )}
                    {horse.isAutoGenerated && (
                      <Badge variant="default" className="text-xs">Auto</Badge>
                    )}
                  </div>
                  <div className="flex items-center gap-3 text-sm text-gray-400 mt-0.5">
                    <span className="flex items-center gap-1">
                      <User className="w-3 h-3" />
                      {horse.ownerName}
                    </span>
                    <span className="flex items-center gap-1">
                      <Trophy className="w-3 h-3" />
                      {horse.jockeyName}
                    </span>
                  </div>
                </div>

                {/* Odds */}
                <div className="text-right">
                  <div className={`text-lg font-bold ${
                    isFavorite(index) ? 'text-gold' : 'text-white'
                  }`}>
                    {horse.odds}
                  </div>
                  <div className="text-xs text-gray-500">odds</div>
                </div>
              </div>

              {/* Silks Description */}
              {horse.silks && horse.silks !== 'Standard colors' && (
                <div className="mt-2 pt-2 border-t border-night-lighter/50">
                  <div className="flex items-start gap-2 text-xs text-gray-500">
                    <Shirt className="w-3 h-3 mt-0.5 flex-shrink-0" />
                    <span className="line-clamp-2">{horse.silks}</span>
                  </div>
                </div>
              )}

              {/* Age and Weight */}
              {(horse.age || horse.weight) && (
                <div className="mt-2 pt-2 border-t border-night-lighter/50 flex items-center gap-4 text-xs text-gray-500">
                  {horse.age && (
                    <span>{horse.age} yrs</span>
                  )}
                  {horse.weight && (
                    <span>{horse.weight}</span>
                  )}
                  {horse.country && (
                    <span className="uppercase">{horse.country}</span>
                  )}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Footer */}
      <div className="p-4 bg-night border-t border-night-lighter">
        <div className="flex items-center justify-between text-sm">
          <span className="text-gray-400">
            Locked at {new Date(raceCard.lockedAt).toLocaleTimeString()}
          </span>
          <span className="text-green-400 flex items-center gap-1">
            ✓ Race Ready
          </span>
        </div>
      </div>
    </div>
  );
}
